const userConstants = {
    USER_LOGIN_REQUEST : 'USER_LOGIN_REQUEST',
    USER_LOGIN_SUCCESS : 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL : 'USER_LOGIN_FAIL',
    USER_LOGOUT : 'USER_LOGOUT',
    USER_REGISTRATION_REQUEST : 'USER_REGISTRATION_REQUEST',
    USER_REGISTRATION_SUCCESS : 'USER_REGISTRATION_SUCCESS',
    USER_REGISTRATION_FAIL : 'USER_REGISTRATION_FAIL',
}

export {
    userConstants
}

